---
title: "Economías Modernas"
date: "3/2020"
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts", "custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

<style>

.center2 {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}

</style>

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = TRUE, echo = FALSE, warning = FALSE)
library(ggplot2)
library(dplyr)
library(cowplot)
library(kableExtra)

theme_set(
  theme_classic() + 
    theme(
      plot.title = element_text(hjust = 0.5)
    ))

demand <- Hmisc::bezier(c(1, 3, 9),
                        c(9, 3, 1)) %>%
  as_data_frame()
```


# Complejidad de las economías modernas

- Ejemplo de una transacción simple como la compra de un pasaje de avión.

- Economías **mixtas**: los recursos se asignan por mecanismos de _mercado_ y directamente por el _estado_.

---
## El mercado como mecanismo de asignación de recursos

- Un mercado es el marco en el que interactúan los *oferentes* y los *demandantes* de un bien, que son los que deciden cuanto compra y venden a cierto precio con el fin de obtener un resultado (ganancia, satisfacción de necesidades, etc.).
- No hay un individuo o empresa responsable de "hacer funcionar" los mercados. Hay mercados de muchos tipos (centralizados, descentralizados, electrónicos, etc.).
- El rol de los mercados es determinar los **precios** y las **cantidades** que se compran de cada bien en la economía (autos, toneladas de celulosa, clases de economía).
- Estos precios sirven como **señales** para los agentes económicos, y son imprescindibles para **coordinar** su acción.
- El **equilibrio** de mercado es una combinación de precios y cantidades que haya un balance entre oferta y demanda, y que no se produzca de más ni de menos.

---
## El mercado como mecanismo de asignación de recursos (2)

- Los mercados son una forma de determinar:
  - ¿Qué producir? Si nadie compra algo, el productor recibe una señal de que no es socialmente deseable destinar recursos a su producción.
  - ¿Cómo producir? Una nueva tecnología de producción será adoptada si aumenta más los ingresos que los costos.
  - ¿Para quién producir? Los ingresos de los miembros de una sociedad se determinan por los precios de los factores productivos que poseen.
  
  
---
- Los principales fuerzas que determinan el funcionamiento de la economía: las preferencias y la tecnología.
- Las preferencias son los gustos de los consumidores, y determinan donde nos vamos a parar en la FPP.
- La tecnología determina los límites de lo que podemos producir con los factores productivos que poseemos.
- El flujo circular
- Adam Smith y el descubrimiento del mercado como mecanismo asignador de recursos.

---

## Tres factores claves en las economías modernas: Comercio

- El comercio permite la división y la **especialización** de los factores productivos: la tierra, el trabajo y el capital.
- La globalización agrandan el tamaño del mercado y aumentan las posibilidades de división del trabajo de forma que un profesor de economía en Uruguay pueda acceder a bienes producidos en China por una empresa de EUA con mano de obra local.

---
## Tres factores claves en las economías modernas: Capital

- En las economías modernas el capital -maquinaria, edificios, etc- tiene un rol fundamental para aumentar la productividad de los trabajadores.

---
## Tres factores claves en las economías modernas: Dinero

- La importancia del dinero para facilitar el intercambio y la especialización. 
- Sin dinero deberíamos usar el trueque, y dependemos de que las personas que producen lo que necesitamos quieran lo que nostros producimos.

---
## El flujo circular de la economía.

Poner imágen.

---
## El rol del Estado

En **competencia perfecta**, el mercado asigna los recursos de manera eficiente. Sin embargo, en una economía mixta, el Estado tiene un rol clave para:

- Corregir situaciones en el que el mercado no funciona en competencia perfecta
  - Monopolios
  - Externalidades

- Corregir resultados eficientes pero injustos (distribución del ingreso demasiado desigual)

- Proveer estabilidad macroeconómica
  - Política Fiscal 
  - Política Monetaria


